part3():-
	formataTexto("Com uma quantidade de força considerável, você abre o portão e se depara com um grande receptáculo que parecia guardar uma chama intensa, três cavaleiros estavam a frente desse receptáculo, estes que não pareciam humanos, pois suas armaduras e pele eram como sombras. Atrás desse grande receptáculo que ardia em chamas, um ser estava sentado num pequeno monte. Ele olhava tranquilo e imponente enquanto permanecia sentado, sua aparência era como de um dragão num corpo de humano, era verde escuro, suas escamas brilhavam refletindo as chamas.\nEntão os 3 cavaleiros vão em sua direção, prepare-se!", Texto),
	write(Texto),
	continuar(),
	write("BatalhaPart3"),
	continuar(),
	formataTexto("???: Ha Ha Ha!", Texto2),
	formataTexto("???: Você foi bem, pequeno humano", Texto3),
	formataTexto("???: A partir daqui a jornada ficará cada vez mais difícil", Texto4),
	formataTexto("???: Seu destino irá mudar, poderá sair daqui com a benção divina ou com a maldição dos demônios", Texto5),
	formataTexto("???: No final, você escolherá seu destino, então siga em frente", Texto6),
	formataTexto("???: O verdadeiro desafio começa agora!", Texto7),
	formataTexto("Continua...", Texto8),
	write(Texto2),
	continuar(),
	write(Texto3),
	continuar(),
	write(Texto4),
	continuar(),
	write(Texto5),
	continuar(),
	write(Texto6),
	continuar(),
	write(Texto7),
	continuar(),
	write(Texto8).
